FROM oven/bun:latest
WORKDIR /app
COPY . .
RUN bun install
EXPOSE 3000
ARG AWS_BUCKET
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_REGION
ARG AWS_ENDPOINT    
ARG AWS_S3_FORCE_PATH_STYLE
ENV NODE_ENV=production
ENV AWS_BUCKET=${AWS_BUCKET}
ENV AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
ENV AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
ENV AWS_REGION=${AWS_REGION}
ENV AWS_ENDPOINT=${AWS_ENDPOINT}
ENV AWS_S3_FORCE_PATH_STYLE=${AWS_S3_FORCE_PATH_STYLE}
CMD ["bun", "run", "src/index.ts"]